### ISSUE TITLE
FiTrash2 is invisible since release 1.0.4 or 1.0.5

### ISSUE THREAD

**Issue by J053Fabi0** [UrielCh/react-icons#4]
## 1.0.5
![image](https://github.com/UrielCh/react-icons/assets/12930717/70b444f8-9da3-40ea-986c-e946526f26ac)

## 1.0.2
![image](https://github.com/UrielCh/react-icons/assets/12930717/55487317-eef1-42b0-afa4-9f2cb75bda67)

**Comment by J053Fabi0** [comment]
Never mind, this is solved in 1.0.8
![image](https://github.com/UrielCh/react-icons/assets/12930717/810545dd-d451-43c1-a1d0-e98bfcaf4ce4)

**Comment by UrielCh** [comment]
you're welcome
